name: CI • BluMonitor


on:
push:
branches: [ main ]
pull_request:
branches: [ main ]


jobs:
lint-test-build:
runs-on: ubuntu-latest
steps:
- name: Checkout
uses: actions/checkout@v4


- name: Set up Python
uses: actions/setup-python@v5
with:
python-version: '3.12'


- name: Install tooling
run: |
python -m pip install --upgrade pip
pip install flake8 black pytest


- name: Lint (flake8)
run: flake8 app src tests || true
# Keeping forgiving for Tier 1; switch to strict later.


- name: Format check (black)
run: black --check app tests


- name: Run unit tests
run: pytest -q


- name: Set up Docker Buildx
tags: blumonitor/app:ci